// preact/src/App.jsx
import { useState } from 'react';
import { DontTranslate, Phrase, Translate, useCurrentLocale, useSignal, useT } from 'langsys-js-react';
import { LOCALES, LOCALE_LABELS, demoBanner, locale } from './langsys';
import './demo.css';

const KEYS_URL = 'https://docs.langsys.dev/learn/concepts/keys-and-environments';
const DOCS_URL = 'https://docs.langsys.dev/learn/sdk/react';

// The Preact demo app: the React demo's code, VERBATIM, running on Preact via
// @preact/preset-vite's react → preact/compat aliasing. That's the point —
// langsys-js-react needs no changes at all. Only this comment, the topbar
// brand, and the tooling files differ from ../react.

/* t() — inline string, in a component. */
function Greeting({ name }) {
    const t = useT();
    return <p>{t('Hello, {name}!', 'Greetings', { name })}</p>;
}

/* t() — plurals. The phrase is written flat; Langsys generates the plural
   forms per locale (the base locale included) and the SDK picks the branch
   from `count`. Nobody types ICU. */
function Inbox({ name }) {
    const t = useT();
    const [count, setCount] = useState(3);
    return (
        <>
            <p>
                {t(
                    'Hello, {name}! You have {count} new messages.',
                    'Greetings',
                    { name, count },
                )}
            </p>
            <Stepper count={count} onChange={setCount} />
        </>
    );
}

/* Phrase — params & markup; %name%/%count% markers avoid JSX brace collisions. */
function CartNote() {
    const [count, setCount] = useState(3);
    return (
        <>
            <Phrase category="Cart" params={{ name: 'Sarah', count }}>
                Hi %name%, you have %count% items in your cart.
            </Phrase>
            <Stepper count={count} onChange={setCount} />
        </>
    );
}

/* Reading signals — React re-renders only on React state, so useSignal
   bridges the base-SDK signal; useCurrentLocale is the loaded-locale shortcut. */
function LocaleBadge() {
    const selected = useSignal(locale);
    const loaded = useCurrentLocale();

    return (
        <footer className="meta" translate="no">
            selected {selected} · loaded {loaded || 'en-US'} ·{' '}
            <a href={DOCS_URL} target="_blank" rel="noopener noreferrer">
                How this works ↗
            </a>
        </footer>
    );
}

function LocalePills() {
    const loaded = useCurrentLocale();
    return (
        <nav className="locales" translate="no">
            {LOCALES.map((code) => (
                <button
                    key={code}
                    className={'pill' + ((loaded || 'en-US') === code ? ' active' : '')}
                    onClick={() => locale.set(code)}
                >
                    {LOCALE_LABELS[code] ?? code}
                </button>
            ))}
        </nav>
    );
}

function Stepper({ count, onChange }) {
    return (
        <div className="stepper" translate="no">
            <button aria-label="Fewer" onClick={() => onChange(Math.max(0, count - 1))}>
                −
            </button>
            <span className="count">{count}</span>
            <button aria-label="More" onClick={() => onChange(count + 1)}>
                +
            </button>
        </div>
    );
}

export default function App() {
    return (
        <>
            {demoBanner && (
                <div className="demo-banner" translate="no">
                    {demoBanner === 'shared' ? (
                        <>
                            <strong>Shared demo project (read-only)</strong> — existing phrases translate; new or
                            edited ones won't. Drop your own keys in <code>.env</code> to watch discovery register and
                            translate your phrases live.
                        </>
                    ) : (
                        <>
                            <strong>No Langsys credentials configured</strong> — showing source text only, nothing
                            translates. Add your project id and key in <code>.env</code> to see it live.
                        </>
                    )}{' '}
                    <a href={KEYS_URL} target="_blank" rel="noopener noreferrer">
                        Get your keys →
                    </a>
                </div>
            )}
            <div className="app">
                <header className="topbar">
                    <div className="brand">
                        <span className="logo">◆</span> <span translate="no">Langsys</span> × Preact
                    </div>
                    <LocalePills />
                </header>

                <section className="card">
                    <h2>
                        <code>t()</code> — inline string, in a component
                    </h2>
                    <div className="live">
                        <Greeting name="Sarah" />
                    </div>
                </section>

                <section className="card">
                    <h2>
                        <code>t()</code> — plurals, written flat
                    </h2>
                    <div className="live">
                        <Inbox name="Sarah" />
                    </div>
                    <p className="hint">
                        Change count to 1 and back — the grammar follows. Every locale applies its own plural rules.
                    </p>
                </section>

                <section className="card">
                    <h2>
                        <code>&lt;Translate&gt;</code> — content block
                    </h2>
                    <div className="live">
                        <Translate category="Home">
                            <h3>Welcome to our store</h3>
                            <p>Browse the catalog in your language.</p>
                        </Translate>
                    </div>
                </section>

                <section className="card">
                    <h2>
                        <code>&lt;Phrase&gt;</code> — params &amp; markup
                    </h2>
                    <div className="live">
                        <CartNote />
                    </div>
                </section>

                <section className="card">
                    <h2>
                        <code>&lt;DontTranslate&gt;</code> — never translated
                    </h2>
                    <div className="live">
                        <Translate category="Tour">
                            <p>
                                Welcome! <DontTranslate>This sentence always stays in English.</DontTranslate> Thanks for visiting!
                            </p>
                        </Translate>
                    </div>
                </section>

                <LocaleBadge />
            </div>
        </>
    );
}

// vue/src/App.vue
<script setup>
// The Vue demo app: every example on docs.langsys.dev/learn/sdk/vue running
// live, wired by the exact code the docs page shows.
import { computed, ref } from 'vue';
import { DontTranslate, Phrase, Translate, useCurrentLocale, useSignal, useT } from 'langsys-js-vue';
import Greeting from './Greeting.vue';
import { LOCALES, LOCALE_LABELS, demoBanner, locale } from './langsys';

const KEYS_URL = 'https://docs.langsys.dev/learn/concepts/keys-and-environments';
const DOCS_URL = 'https://docs.langsys.dev/learn/sdk/vue';

const t = useT();
const name = 'Sarah';

/* t() — plurals. The phrase is written flat; Langsys generates the plural
   forms per locale (the base locale included) and the SDK picks the branch
   from `count`. Nobody types ICU. */
const MSG = 'Hello, {name}! You have {count} new messages.';
const messages = ref(3);

/* Phrase — params & markup. */
const items = ref(3);

/* Reading signals — Vue tracks only its own refs, so useSignal bridges the
   base-SDK signal; useCurrentLocale is the loaded-locale shortcut. */
const selected = useSignal(locale);
const loaded = useCurrentLocale();
const loadedOrDefault = computed(() => loaded.value || 'en-US');
</script>

<template>
    <div v-if="demoBanner" class="demo-banner" translate="no">
        <template v-if="demoBanner === 'shared'">
            <strong>Shared demo project (read-only)</strong> — existing phrases translate; new or edited ones won't.
            Drop your own keys in <code>.env</code> to watch discovery register and translate your phrases live.
        </template>
        <template v-else>
            <strong>No Langsys credentials configured</strong> — showing source text only, nothing translates. Add
            your project id and key in <code>.env</code> to see it live.
        </template>
        <a :href="KEYS_URL" target="_blank" rel="noopener noreferrer">Get your keys →</a>
    </div>

    <div class="app">
        <header class="topbar">
            <div class="brand"><span class="logo">◆</span> <span translate="no">Langsys</span> × Vue</div>
            <nav class="locales" translate="no">
                <button
                    v-for="code in LOCALES"
                    :key="code"
                    class="pill"
                    :class="{ active: loadedOrDefault === code }"
                    @click="locale.set(code)"
                >
                    {{ LOCALE_LABELS[code] ?? code }}
                </button>
            </nav>
        </header>

        <section class="card">
            <h2><code>t()</code> — inline string, in a component</h2>
            <div class="live"><Greeting /></div>
        </section>

        <section class="card">
            <h2><code>t()</code> — plurals, written flat</h2>
            <p class="live">{{ t(MSG, 'Greetings', { name, count: messages }) }}</p>
            <div class="stepper" translate="no">
                <button aria-label="Fewer" @click="messages = Math.max(0, messages - 1)">−</button>
                <span class="count">{{ messages }}</span>
                <button aria-label="More" @click="messages++">+</button>
            </div>
            <p class="hint">Change count to 1 and back — the grammar follows. Every locale applies its own plural rules.</p>
        </section>

        <section class="card">
            <h2><code>&lt;Translate&gt;</code> — content block</h2>
            <div class="live">
                <Translate category="Home">
                    <h3>Welcome to our store</h3>
                    <p>Browse the catalog in your language.</p>
                </Translate>
            </div>
        </section>

        <section class="card">
            <h2><code>&lt;Phrase&gt;</code> — params &amp; markup (<code>%name%</code>)</h2>
            <div class="live">
                <Phrase category="Cart" :params="{ name: 'Sarah', count: items }">
                    Hi %name%, you have %count% items in your cart.
                </Phrase>
            </div>
            <div class="stepper" translate="no">
                <button aria-label="Fewer" @click="items = Math.max(0, items - 1)">−</button>
                <span class="count">{{ items }}</span>
                <button aria-label="More" @click="items++">+</button>
            </div>
        </section>

        <section class="card">
            <h2><code>&lt;DontTranslate&gt;</code> — never translated</h2>
            <div class="live">
                <Translate category="Tour">
                    <p>Welcome! <DontTranslate>This sentence always stays in English.</DontTranslate> Thanks for visiting!</p>
                </Translate>
            </div>
        </section>

        <footer class="meta" translate="no">
            selected {{ selected }} · loaded {{ loadedOrDefault }} ·
            <a :href="DOCS_URL" target="_blank" rel="noopener noreferrer">How this works ↗</a>
        </footer>
    </div>
</template>
